---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1sra0v6924k7y32sr6p0ktw72vufsahfw270dknw9za0x39v0lf2scf38uc
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1sra0v6924k7y32sr6p0ktw72vufsahfw270dknw9za0x39v0lf2scf38uc
