# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:7bL++6+4rn2VMKz4ulF5etXF,iv:J32YJ2oYKqUDGEXTyY50+AgSQmLsd5Umo+9tVUo8qjk=,tag:SMq+QIUF1ZPS8qTBfchTrw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:BAkwuK4VddfeaQG+PCeeLvHeRd83oOrL,iv:MUYcUZ2g6yNUjn0tXHRhsGmy3DKt6oznt8f48Khz5oQ=,tag:cndrV1wJOvJVsA/dMXoriQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sra0v6924k7y32sr6p0ktw72vufsahfw270dknw9za0x39v0lf2scf38uc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZnJzQlA5eEdKcExpTG9l
            emkyZk9vV3poOEs4MzBnVlNEeDBVTzlXMVFjCnRIK01ZVGZ2SERHSVU4emNBNDhr
            OXBMWUVvZHBBUFZkSDliL3dkNFlaaDAKLS0tIEdoVVpNT1NIa3RGaTY5bVVkWkNs
            VSt4TTZaWHp2SHJodU5FK3MyRXN6RmMKEaFlrPjCkoT2B4QseCxLswzBJsnqEGYh
            4g/6bNd2vNZr9O0EQwT7cUAZLOVl7flMHTGQyz6b+RT56F2CWDvG1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-02T01:05:46Z"
    mac: ENC[AES256_GCM,data:K4k1w6ettO4yvemjj6lNTJtp1KwpkFXHwY/A5m7KchacbTPeYdZtbUyeUujZPiygtWA0LcWIuxfTinxSxFixxK8zj25pVjCHrsmO01lxxrgQzSTMi9P6Qw6I60wrBhQW1gxY0sqRf5QAkqQPgWTsMZLQb/so4TVdWFeC82ayZ6Q=,iv:wcovsEnQla3Q/05d2GObsQcf7BkwXI1zwtifEMbw8Js=,tag:e3380UUH+fxlQqYCXQ8Tkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
