# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:PcgvIm9hq8tC7FbCbXTrJ7Z9+lwpwOCVPNyr2VsMmIWMlNu9oA==,iv:NMFHhZSIgk4Eg6ACCz1FW5N1H2pyeWmh0WbXsZKNywA=,tag:BK2l9oYUzVo3U8FvlCZlwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sra0v6924k7y32sr6p0ktw72vufsahfw270dknw9za0x39v0lf2scf38uc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcUFRaHpuZ0FuZk1sZS8y
            Z2ZjcDVYZVVZQjJseXFWY095STFpUFVHZWtJClR6M0JKZDFJc05RNWw2dStGQ21k
            V25yNHVIUHJNbk0rdTRyUVl4VFdkMncKLS0tIFd2QVVPQ2Z4ck5VSjMyUzlSWGpH
            VUcvd1JaVHl3SFEyTUs0SWRZRDgxVkUKgCirx9zSjPO80AsKjIp8zlh/HAJvIYb/
            qq/CyJWPQ8PzWRhyO2SukokQkamgV6sgnQaYPhe7mnEkobfymzf8Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-02T01:05:46Z"
    mac: ENC[AES256_GCM,data:9noU23KTtG77FXE2Yh4j3GemrKvc03T5Nd+CxbAZIvD5wsK0s78uUWlnd0cDh/J5E+NwRtex8JfC+dz063dgmC9I5nt3WR2Ro2BCJLqrDZdlbhSMS320NJgLmpvbnShs+0Tkk5r0982awQG7qbp2DLgIG+N9ULH/TUXni8w2Epw=,iv:/7vy7M+0XG4OSO/W3K7aoy3g1enrGLzY5/ejSN11mtU=,tag:++uAzL5/zVCxFlKyuf3k2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
